"use client"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import Image from "next/image"
import { useState } from "react"
import { PromptText } from "@/components/prompt-text"

// Define types for better type safety
type CategoryId = 'logos' | 'icons' | 'illustrations';

type ExampleItem = {
  prompt: string;
  image: string;
  alt: string;
};

type ExamplesData = {
  [key in CategoryId]: ExampleItem[];
};

export default function UseCases() {
  const [showAllLogos, setShowAllLogos] = useState(false)
  const [showAllIcons, setShowAllIcons] = useState(false)
  const [showAllIllustrations, setShowAllIllustrations] = useState(false)

  const categories: { id: CategoryId, label: string, shortLabel: string }[] = [
    { id: 'logos', label: "AI SVG Logos & Branding", shortLabel: "Logos" },
    { id: 'illustrations', label: "AI SVG Illustrations & Art", shortLabel: "Illustrations" },
    { id: 'icons', label: "AI SVG Icons & UI Elements", shortLabel: "Icons" },
  ]

  const examples: ExamplesData = {
    logos: [
      // Removed oak leaf logo since it's now in the hero section
      {
        prompt: "Modern abstract shield shape logo outline in a metallic cool grey (#B0C4DE), inside the shield is not a flat fill but an abstract visualization of upward-trending data lines composed of small, interconnected glowing blue (#007FFF) blocks, suggesting digital security and growth, sharp clean vector lines",
        image: "/svg-examples/modern-abstract-shield-shape-logo-outline-in-a-met.svg",
        alt: "Modern abstract shield logo with upward-trending data lines for secure finance or crypto brand identity"
      },
      // Removed brain logo since it's now in the hero section
      {
        prompt: "Geometric logo using the abstract shape of a capital letter 'A', where one leg of the 'A' subtly transforms into the nib of a fountain pen, constructed with sharp lines and negative space, bold ochre (#CC7722) and deep teal (#008080) colors, sophisticated and artistic",
        image: "/svg-examples/geometric-logo-using-the-abstract-shape-of-a-capit.svg",
        alt: "Creative agency logo with abstract A shape transforming into fountain pen nib - artistic brand identity"
      },
      {
        prompt: "Playful logo of a whisk where the wire loops are subtly stylized to look like dynamic swooshes or motion lines, creating a sense of speed, with tiny, colorful abstract shapes (red #FF0000, yellow #FFFF00, green #008000) appearing to be 'mixed' or trailing from the motion, clean vector, energetic feel",
        image: "/svg-examples/playful-logo-of-a-whisk-where-the-wire-loops-are-s.svg",
        alt: "Playful food delivery app logo with whisk and colorful motion elements - energetic culinary brand identity"
      },
      {
        prompt: "A minimalist mountain logo with blue gradient",
        image: "/svg-examples/a-minimalist-mountain-logo-with-blue-gradient.svg",
        alt: "Minimalist mountain logo with blue gradient generated by AI SVG generator - outdoor adventure brand identity"
      },
      {
        prompt: "A minimalist tech startup logo with modern design",
        image: "/svg-examples/a-minimalist-svg-logo-for-a-tech-startup-the-design.svg",
        alt: "Minimalist tech startup logo generated by AI - modern corporate identity design"
      },
      {
        prompt: "A clean single line art logo for an organic coffee shop",
        image: "/svg-examples/-clean-single-line-art-logo-for-an-organic-coffee-.svg",
        alt: "Clean single line art coffee shop logo generated by AI SVG generator - organic brand identity"
      },
      {
        prompt: "A minimalist fish logo for a seafood business",
        image: "/svg-examples/fish-logo.svg",
        alt: "Minimalist fish logo design generated by AI SVG tool - sleek aquatic business symbol"
      },
      {
        prompt: "Hand-drawn style coffee cup logo for a cafe, steaming coffee, single line art, warm brown color (#A0522D), friendly typography element saying 'Cafe'",
        image: "/svg-examples/hand-drawn-style-coffee-cup-logo-for-a-cafe-steami.svg",
        alt: "Hand-drawn style coffee cup logo with steam for a cafe - AI generated artisanal brand design"
      },
      // Removed fox logo example (already in hero)
      {
        prompt: "Strong mountain peak logo silhouette, three peaks, minimalist design, solid deep navy blue (#000080), representing stability and growth",
        image: "/svg-examples/strong-mountain-peak-logo-silhouette-three-peaks-m.svg",
        alt: "Strong mountain peak logo silhouette with three peaks - AI generated outdoor adventure brand identity"
      },
      {
        prompt: "Abstract technology startup logo representing connectivity, intertwined blue (#007BFF) and green (#28A745) circuits, modern, flat design",
        image: "/svg-examples/abstract-technology-startup-logo-representing-conn.svg",
        alt: "Abstract technology startup logo representing connectivity - AI generated tech brand identity"
      },
      {
        prompt: "A collection of minimalist logo marks for AI startups",
        image: "/svg-examples/minimalist-ai-startup-logo-collection.svg",
        alt: "Collection of minimalist AI startup logo marks created by text-to-SVG AI - modern branding elements"
      },
    ],
    icons: [
      {
        prompt: "Clean UI icon combining a classic speech bubble outline with a subtle, simplified neural network pattern faintly visible inside it, single color vibrant electric blue (#00FFFF), thin consistent line weight",
        image: "/svg-examples/clean-ui-icon-combining-a-classic-speech-bubble-ou.svg",
        alt: "AI assistant chatbot icon with speech bubble and neural network - conversational interface symbol"
      },
      {
        prompt: "Modern flat UI icon showing a stylized cloud shape, with two curved arrows forming a cycle overlaying the cloud, and subtle, faint binary code pattern (0s and 1s) filling the cloud shape, primary color soft blue (#ADD8E6) with darker blue (#0000CD) arrows",
        image: "/svg-examples/modern-flat-ui-icon-showing-a-stylized-cloud-shape.svg",
        alt: "Data synchronization cloud icon with cycle arrows and binary pattern - cloud sync user interface element"
      },
      {
        prompt: "Creative search UI icon showing a magnifying glass where the circular lens area contains three concentric, layered circles or a simplified funnel shape, representing filtering or drilling down into results, clean outline style, single dark grey color (#A9A9A9)",
        image: "/svg-examples/creative-search-ui-icon-showing-a-magnifying-glass.svg",
        alt: "Advanced search UI icon with magnifying glass and concentric circles - filtering interface element"
      },
      {
        prompt: "Engaging UI icon for achievement unlocked, showing a simple trophy or badge silhouette with small sparkles or a subtle upward-pointing glowing effect emanating from the top, indicating progress or success, main shape in gold color (#FFD700) with white (#FFFFFF) sparkles/glow, flat style with subtle gradient on trophy",
        image: "/svg-examples/engaging-ui-icon-for-achievement-unlocked-showing.svg",
        alt: "Achievement gamification icon with trophy and upward glowing effect - user reward interface element"
      },
      {
        prompt: "Essential UI icons set for web and mobile interfaces",
        image: "/svg-examples/essential-ui-icons-set.svg",
        alt: "Essential UI icons set generated by AI - basic interface elements including home, check, settings and email icons"
      },
      {
        prompt: "E-commerce UI icons set with shopping elements",
        image: "/svg-examples/ecommerce-ui-icons-set.svg",
        alt: "E-commerce UI icons set created with text-to-SVG AI - shopping, home, search and location interface elements"
      },
      {
        prompt: "A futuristic technology icon set including symbols",
        image: "/svg-examples/a-futuristic-technology-icon-set-including-symbols.svg",
        alt: "Futuristic technology icon set by AI SVG generator - modern tech symbols collection"
      },
      {
        prompt: "Set of 4 outline style UI icons: user profile, settings gear, notification bell, shopping cart, single color dark grey (#696969), thin lines, clean and simple",
        image: "/svg-examples/set-of-4-outline-style-ui-icons-user-profile-setti.svg",
        alt: "Set of 4 outline style UI icons created with AI - user profile, settings, notification, and search elements"
      },
      // Removed business dashboard analytics icon since it's now in the hero section
      {
        prompt: "Computer workstation icon: minimalist desktop setup",
        image: "/svg-examples/computer-workstation-icon.svg",
        alt: "Minimalist computer workstation icon - clean lined office setup interface element"
      },
      {
        prompt: "Productivity calendar icons showing organization tools",
        image: "/svg-examples/productivity-calendar-icons.svg",
        alt: "Productivity calendar icons for organizational apps - time management UI elements"
      },
      {
        prompt: "Engraving style book icon for a library app, detailed lines, single dark brown color (#8B4513), vintage feel",
        image: "/svg-examples/engraving-style-book-icon-for-a-library-app-detail.svg",
        alt: "Detailed engraving style book icon for library applications - vintage literature interface element"
      },
      {
        prompt: "Simple checkmark icon inside a circle, outline style, success green color (#2E8B57), clean thin lines",
        image: "/svg-examples/simple-checkmark-icon-inside-a-circle-outline-styl.svg",
        alt: "Simple checkmark icon in circle with clean outline style - confirmation or success interface element"
      },
    ],
    illustrations: [
      {
        prompt: "A vibrant abstract SVG background with overlapping shapes",
        image: "/svg-examples/a-vibrant-abstract-svg-background-with-overlapping.svg",
        alt: "Vibrant abstract SVG background with colorful overlapping shapes - decorative website element created with AI"
      },
      {
        prompt: "Line art illustration of a bustling cityscape at night, skyscrapers with glowing windows, stars above, single dark blue (#00008B) line color on white background",
        image: "/svg-examples/line-art-illustration-of-a-bustling-cityscape-at-n.svg",
        alt: "Line art illustration of bustling night cityscape - urban environment vector graphic generated by AI"
      },
      {
        prompt: "Abstract pattern of flowing organic shapes and leaves, autumn colors (red #DC143C, orange #FF8C00, yellow #FFD700, brown #A0522D), seamless tileable design",
        image: "/svg-examples/abstract-pattern-of-flowing-organic-shapes-and-lea.svg",
        alt: "Abstract pattern with flowing organic shapes and leaves - decorative vector background created with AI"
      },
      {
        prompt: "Detailed engraving style illustration of various sea creatures (octopus, fish, seahorse), intricate lines, single deep sea blue color (#000080), vintage scientific illustration feel",
        image: "/svg-examples/detailed-engraving-style-illustration-of-various-s.svg",
        alt: "Detailed engraving style illustration with vintage aesthetic - AI generated vector artwork"
      },
      // Removed cute cartoon astronaut since it's now in the hero section
      {
        prompt: "Abstract wave pattern art with flowing lines",
        image: "/svg-examples/abstract-wave-pattern-art.svg",
        alt: "Abstract wave pattern art with flowing lines - decorative SVG background generated by AI"
      },
      {
        prompt: "Futuristic cityscape at night with neon elements",
        image: "/svg-examples/futuristic-cityscape-night.svg",
        alt: "Futuristic night cityscape with neon elements - cyberpunk urban vector illustration created by AI"
      },
      {
        prompt: "Linocut style portrait of a woman reading a book under a tree, high contrast black and white, strong graphic shapes, peaceful mood",
        image: "/svg-examples/linocut-style-portrait-of-a-woman-reading-a-book-u.svg",
        alt: "Linocut style portrait of woman reading book - artistic woodcut-inspired vector illustration by AI"
      },
      {
        prompt: "Diverse people illustrations for inclusive design",
        image: "/svg-examples/diverse-people-illustrations.svg",
        alt: "Diverse people illustrations for inclusive design - multicultural character set generated by AI"
      },
      {
        prompt: "An educational infographic showing a circular life cycle",
        image: "/svg-examples/an-educational-infographic-showing-a-circular-life.svg",
        alt: "Educational infographic with circular life cycle - instructional vector diagram created with AI"
      },
      // Removed cute red panda since it's now in the hero section
      {
        prompt: "Romantic couple silhouette against sunset",
        image: "/svg-examples/romantic-couple-silhouette.svg",
        alt: "Romantic couple silhouette against sunset backdrop - emotional relationship illustration by AI"
      },
      {
        prompt: "Data center server infrastructure diagram",
        image: "/svg-examples/data-center-server-infrastructure.svg",
        alt: "Data center server infrastructure diagram - technical IT illustration created with AI"
      },
      // Removed business dashboard analytics since it's now in the hero section
      {
        prompt: "iPhone models comparison illustration",
        image: "/svg-examples/iphone-models-illustration.svg",
        alt: "iPhone models comparison illustration - device lineup vector graphic created by AI"
      },
      {
        prompt: "Renewable energy sustainability concept illustration",
        image: "/svg-examples/renewable-energy-sustainability.svg",
        alt: "Renewable energy sustainability concept illustration - eco-friendly power solutions vector graphic by AI"
      },
      {
        prompt: "AI startup neural network visualization",
        image: "/svg-examples/ai-startup-neural-network.svg",
        alt: "AI startup neural network visualization - machine learning concept vector illustration created with AI"
      },
      // Added tiger illustration that was removed from hero
      {
        prompt: "Close-up wildlife illustration of a tiger's eye with intricate detail",
        image: "/svg-examples/eye-of-the-tiger.svg",
        alt: "Close-up tiger eye illustration with striking detail - wildlife vector artwork created by AI"
      },
    ],
  }

  // Function to get displayed items based on 'show all' state
  function getDisplayedItems(category: CategoryId, showAll: boolean): ExampleItem[] {
    return showAll ? examples[category] : examples[category].slice(0, 6);
  }

  return (
    <section id="use-cases" className="py-16 md:py-24 bg-brand/50">
      <div className="container mx-auto px-4">
        {/* Added SEO-friendly H2 heading */}
        <h2 className="text-3xl md:text-4xl font-extrabold text-center text-gray-800 mb-12">
          Explore AI-Generated SVGs: From Text to Vector Graphics
        </h2>
        <Tabs defaultValue="illustrations" className="w-full">
          <TabsList className="grid w-full grid-cols-3 max-w-3xl mx-auto bg-gray-100 rounded-lg p-1 mb-8">
            {categories.map((category) => (
              <TabsTrigger 
                key={category.id} 
                value={category.id} 
                className="px-2 py-1.5 md:px-3 md:py-2"
              >
                <span className="hidden md:inline">{category.label}</span>
                <span className="md:hidden">{category.shortLabel}</span>
              </TabsTrigger>
            ))}
          </TabsList>

          {categories.map((category) => (
            <TabsContent key={category.id} value={category.id}>
              <div className="bg-brand rounded-xl p-6 md:p-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {getDisplayedItems(category.id, category.id === 'logos' ? showAllLogos : category.id === 'icons' ? showAllIcons : showAllIllustrations).map((item, index) => (
                  <div key={index} className="rounded-xl overflow-hidden border border-slate-100 shadow-sm hover:shadow-md transition-shadow bg-white">
                    <div className="aspect-square bg-slate-50 flex items-center justify-center p-4">
                      <Image 
                        src={item.image} 
                        alt={item.alt}
                        width={200}
                        height={200}
                        className="object-contain w-full h-full"
                        loading={index < 6 ? "eager" : "lazy"}
                      />
                    </div>
                    <div className="p-4">
                      <h3 className="font-medium text-sm text-gray-700 dark:text-gray-300">Prompt:</h3>
                      <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">
                        <PromptText text={item.prompt} maxLength={50} />
                      </p>
                    </div>
                  </div>
                ))}
              </div>
              {examples[category.id].length > 6 && (
                <div className="mt-8 text-center">
                  <button
                    onClick={() => {
                      if (category.id === 'logos') setShowAllLogos(!showAllLogos)
                      if (category.id === 'icons') setShowAllIcons(!showAllIcons)
                      if (category.id === 'illustrations') setShowAllIllustrations(!showAllIllustrations)
                    }}
                    className="inline-flex items-center px-4 py-2 rounded-md border border-gray-300 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary"
                  >
                    {(category.id === 'logos' && showAllLogos) || (category.id === 'icons' && showAllIcons) || (category.id === 'illustrations' && showAllIllustrations) ? 'Show Less' : `View ${examples[category.id].length - 6} More ${category.label}`}
                  </button>
                </div>
              )}
            </TabsContent>
          ))}
        </Tabs>
      </div>
    </section>
  )
}
