import fs from 'fs';
import path from 'path';

export type SVGExample = {
  src: string;
  alt: string;
  type: string;
  description: string;
  svgContent?: string; // The actual SVG markup
};

// Define the examples structure (same as in your Hero component)
export const exampleSVGs: SVGExample[] = [
  {
    src: "/svg-examples/summer-music-festival-poster.svg",
    alt: "Summer music festival poster SUNSET VIBES 2025 with palm trees and neon colors generated by AI",
    type: "Event Poster",
    description: "Vibrant festival poster with text integration. Create professional event designs with AI in seconds."
  },
  {
    src: "/svg-examples/mom.svg",
    alt: "Mother and child illustration SVG generated by AI",
    type: "Family Illustration",
    description: "Heartwarming mother and child design. Perfect for family-oriented brands, Mother's Day content, or parenting blogs."
  },
  {
    src: "/svg-examples/ecommerce-ui-icons-set.svg",
    alt: "E-commerce SVG UI icon set generated by AI",
    type: "Icon Set",
    description: "Cohesive e-commerce icon set for UI/UX. Create custom SVG icons instantly with a single prompt."
  },
  {
    src: "/svg-examples/e-learning-course.svg",
    alt: "E-learning course banner MASTER PYTHON IN 30 DAYS with code snippets and progress bar generated by AI",
    type: "Course Banner",
    description: "Professional education banner with course details. Perfect for online learning platforms and course marketing."
  },
  {
    src: "/svg-examples/cute-red-panda-mascot.svg",
    alt: "Cute red panda mascot SVG generated by AI",
    type: "Brand Mascot",
    description: "Charming red panda mascot, perfect for playful branding or apps. Instantly created by AI from text."
  },
  {
    src: "/svg-examples/minimalist-geometric-fox-head-logo-clean-lines-sin.svg",
    alt: "Minimalist geometric fox head SVG logo generated by AI",
    type: "Brand Logo",
    description: "Clean, modern fox logo created with AI. Perfect for businesses looking for a distinctive mark."
  },
  {
    src: "/svg-examples/cute-avocado.svg",
    alt: "Cute avocado character expressions emoji set generated by AI",
    type: "Character Design",
    description: "Adorable avocado characters with 6 expressions. Perfect for stickers, merch, or social media content."
  },
  {
    src: "/svg-examples/minimalist-logo-of-a-stylized-human-brain-profile-.svg",
    alt: "Stylized human brain SVG logo with neural network pattern generated by AI",
    type: "AI Brain Logo",
    description: "Futuristic brain logo with neural network design—showcasing AI's creative power for tech branding."
  },
  {
    src: "/svg-examples/instagram-post-template-set-with-3-designs-new-arr.svg",
    alt: "Instagram post template set with NEW ARRIVAL badge, FOLLOW US text, and SWIPE FOR MORE designs generated by AI",
    type: "Social Media Pack",
    description: "Ready-to-use Instagram templates for businesses. Create entire social media campaigns with one prompt."
  }
];

// Use a simpler implementation that doesn't try to read files from disk
export async function getExampleSVGs(): Promise<SVGExample[]> {
  // Just return the metadata without trying to read SVG content
  // This works better for both development and production
  return exampleSVGs;
}
