export type SVGExample = {
  src: string;
  alt: string;
  type: string;
  description: string;
  thumbnail?: string; // Low quality placeholder
};

// Only include essential examples for the hero, load rest on demand
export const heroExamples: SVGExample[] = [
  {
    src: "/svg-examples/summer-music-festival-poster.svg",
    alt: "Summer music festival poster SUNSET VIBES 2025 with palm trees and neon colors generated by AI",
    type: "Event Poster",
    description: "Vibrant festival poster with text integration. Create professional event designs with AI in seconds.",
    thumbnail: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' fill='%23f3f4f6'/%3E%3C/svg%3E"
  },
  {
    src: "/svg-examples/mom.svg",
    alt: "Mother and child illustration SVG generated by AI",
    type: "Family Illustration",
    description: "Heartwarming mother and child design. Perfect for family-oriented brands, Mother's Day content, or parenting blogs.",
    thumbnail: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' fill='%23f3f4f6'/%3E%3C/svg%3E"
  },
  {
    src: "/svg-examples/ecommerce-ui-icons-set.svg",
    alt: "E-commerce SVG UI icon set generated by AI",
    type: "Icon Set",
    description: "Cohesive e-commerce icon set for UI/UX. Create custom SVG icons instantly with a single prompt.",
    thumbnail: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' fill='%23f3f4f6'/%3E%3C/svg%3E"
  },
  {
    src: "/svg-examples/minimalist-geometric-fox-head-logo-clean-lines-sin.svg",
    alt: "Minimalist geometric fox head SVG logo generated by AI",
    type: "Brand Logo",
    description: "Clean, modern fox logo created with AI. Perfect for businesses looking for a distinctive mark.",
    thumbnail: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' fill='%23f3f4f6'/%3E%3C/svg%3E"
  },
  {
    src: "/svg-examples/dog.svg",
    alt: "Adorable illustrated dog character with expressive eyes and playful stance SVG generated by AI",
    type: "Character Illustration",
    description: "Charming dog illustration perfect for pet brands, children's content, or friendly mascots.",
    thumbnail: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' fill='%23f3f4f6'/%3E%3C/svg%3E"
  }
];

// Lazy load additional examples
export async function loadAdditionalExamples(): Promise<SVGExample[]> {
  // This would load from the full svg-examples.ts file
  const { exampleSVGs } = await import('./svg-examples');
  return exampleSVGs.slice(5); // Skip the ones already loaded
}