import fs from 'fs';
import path from 'path';

export type SVGExample = {
  src: string;
  alt: string;
  type: string;
  description: string;
  svgContent?: string; // The actual SVG markup
};

// Define the examples structure (same as in your Hero component)
export const exampleSVGs: SVGExample[] = [
  {
    src: "/svg-examples/minimalist-geometric-fox-head-logo-clean-lines-sin.svg",
    alt: "Minimalist geometric fox head SVG logo generated by AI",
    type: "Brand Logo",
    description: "Clean, modern fox logo created with AI. Perfect for businesses looking for a distinctive mark."
  },
  {
    src: "/svg-examples/cute-red-panda-mascot.svg",
    alt: "Cute red panda mascot SVG generated by AI",
    type: "Brand Mascot",
    description: "Charming red panda mascot, perfect for playful branding or apps. Instantly created by AI from text."
  },
  {
    src: "/svg-examples/business-dashboard-analytics.svg",
    alt: "Business dashboard analytics SVG generated by AI",
    type: "Dashboard Graphic",
    description: "Professional dashboard SVG for analytics or SaaS. AI turns your ideas into ready-to-use vector graphics."
  },
  {
    src: "/svg-examples/dog.svg",
    alt: "Detailed dog SVG illustration generated by AI",
    type: "Pet Illustration",
    description: "Highly detailed dog illustration—ideal for pet brands, blogs, or print. Generated in seconds using AI."
  },
  {
    src: "/svg-examples/ecommerce-ui-icons-set.svg",
    alt: "E-commerce SVG UI icon set generated by AI",
    type: "Icon Set",
    description: "Cohesive e-commerce icon set for UI/UX. Create custom SVG icons instantly with a single prompt."
  },
  {
    src: "/svg-examples/minimalist-logo-of-a-stylized-human-brain-profile-.svg",
    alt: "Stylized human brain SVG logo with neural network pattern generated by AI",
    type: "AI Brain Logo",
    description: "Futuristic brain logo with neural network design—showcasing AI's creative power for tech branding."
  },
  {
    src: "/svg-examples/logo-featuring-a-detailed-oak-leaf-where-the-veins.svg",
    alt: "Corporate oak leaf SVG logo generated by AI",
    type: "Corporate Logo",
    description: "Elegant oak leaf logo, perfect for eco-friendly brands. Instantly generated from a simple text prompt."
  },
  {
    src: "/svg-examples/cute-cartoon-astronaut-floating-in-space-next-to-a.svg",
    alt: "Cute astronaut SVG illustration generated by AI",
    type: "Mascot Illustration",
    description: "Adorable astronaut mascot, ready for tech or education projects. Created with AI-powered SVG generation."
  }
];

// Use a simpler implementation that doesn't try to read files from disk
export async function getExampleSVGs(): Promise<SVGExample[]> {
  // Just return the metadata without trying to read SVG content
  // This works better for both development and production
  return exampleSVGs;
}
